SystemNFO/SystemNFO/Controllers/CurController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SystemNFO.Models;

namespace SystemNFO.Controllers
{
    public class CurController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cur
        public ActionResult Index()
        {
            return View(db.Curs.ToList());
        }
        public ActionResult GetOrganizations()
        {
            var organizations = db.Curs.ToList();
            return PartialView(organizations);
        }
        public ActionResult GetOrganizations1()
        {
            var organizations = db.Curs.ToList();
            return PartialView(organizations);
        }
        public ActionResult Index1()
        {
            return View(db.Organizations.ToList());
        }
        // GET: Cur/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cur cur = db.Curs.Find(id);
            if (cur == null)
            {
                return HttpNotFound();
            }
            return View(cur);
        }

        // GET: Cur/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cur/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CurId,Ogrn,Socrnameorg")] Cur cur)
        {
            if (ModelState.IsValid)
            {
                db.Curs.Add(cur);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cur);
        }

        // GET: Cur/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cur cur = db.Curs.Find(id);
            if (cur == null)
            {
                return HttpNotFound();
            }
            return View(cur);
        }

        // POST: Cur/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CurId,Ogrn,Socrnameorg")] Cur cur)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cur).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cur);
        }

        // GET: Cur/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cur cur = db.Curs.Find(id);
            if (cur == null)
            {
                return HttpNotFound();
            }
            return View(cur);
        }

        // POST: Cur/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cur cur = db.Curs.Find(id);
            db.Curs.Remove(cur);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SystemNFO/SystemNFO/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlTypes;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SystemNFO.Models;

namespace SystemNFO.Controllers
{
    public class OrganizationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //[HttpGet]
        //public ActionResult CreateEmp()
        //{ 
        //    SelectList employees = new SelectList(db.Employees, "EmployeeId", "FIO");
        //      ViewBag.Employees = employees;
         
        //}

        public ActionResult Index()
        {
            return View(db.Organizations.ToList());
        }
        public ActionResult Index2()
        {
            return View(db.Events.ToList());
        }
        public ActionResult Index4()
        {
            return View(db.Events.ToList());
        }
        public ActionResult Index3()
        {
            return View(db.SuperModes.ToList());
        }
        public ActionResult GetOrganizations()
        {
            var organizations = db.Organizations.ToList();
            return PartialView(organizations);
        }
        public ActionResult GetOrganizations1()
        {
            var organizations = db.Organizations.ToList();
            return PartialView(organizations);
        }
        public ActionResult GetOrganizations2()
        {
            var organizations = db.Organizations.ToList();
            return PartialView(organizations);
        }
        public ActionResult Index1()
        {
            return View(db.Organizations.ToList());
        }

        [HttpGet]
        public ActionResult ListOrganizations()
        {
            var organizations = db.Organizations.ToList();

            var viewModel = new ListOrganizationViewModel { Organizations = organizations };

            return View(viewModel);
        }
       
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

       
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Create4()
        {
            return View();
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create4([Bind(Include = "EventId,Nameevent,Comment,Databegin,Status,Dataend,Dataperenos,Dataplan,Datacontrol,Nadzorfact,Result,Mode")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index4");
            }

            return View(@event);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrganizationId,Ogrn,Nameorg,Socrnameorg,Status,Vidorg,Category,Risc,Mode")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Organizations.Add(organization);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(organization);
        }
    
        public ActionResult Create1()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create1([Bind(Include = "OrganizationId,Ogrn,Nameorg,Socrnameorg,Status,Vidorg,Category,Risc,Mode")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Organizations.Add(organization);
                db.SaveChanges();
                return RedirectToAction("Index1");
            }

            return View(organization);
        }

        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }
     
        public ActionResult Edit1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrganizationId,Ogrn,Nameorg,Socrnameorg,Status,Vidorg,Category,Risc,Mode")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Entry(organization).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(organization);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit1([Bind(Include = "OrganizationId,Ogrn,Nameorg,Socrnameorg,Status,Vidorg,Category,Risc,Mode")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Entry(organization).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index1");
            }
            return View(organization);
        }

      
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }
        
        public ActionResult Delete1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Organization organization = db.Organizations.Find(id);
            db.Organizations.Remove(organization);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SystemNFO/SystemNFO/Controllers/SuperModeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SystemNFO.Models;

namespace SystemNFO.Controllers
{
    public class SuperModeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SuperMode
        public ActionResult Index()
        {
            return View(db.SuperModes.ToList());
        }
        public ActionResult GetModes()
        {
            var modes = db.SuperModes.ToList();
            return PartialView(modes);
        }
        // GET: SuperMode/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SuperMode superMode = db.SuperModes.Find(id);
            if (superMode == null)
            {
                return HttpNotFound();
            }
            return View(superMode);
        }

        // GET: SuperMode/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SuperMode/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SuperModeId,Ogrn,Date,Document,Vid,Category,Mode,Namemode")] SuperMode superMode)
        {
            if (ModelState.IsValid)
            {
                db.SuperModes.Add(superMode);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(superMode);
        }

        // GET: SuperMode/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SuperMode superMode = db.SuperModes.Find(id);
            if (superMode == null)
            {
                return HttpNotFound();
            }
            return View(superMode);
        }

        // POST: SuperMode/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SuperModeId,Ogrn,Date,Document,Vid,Category,Mode,Namemode")] SuperMode superMode)
        {
            if (ModelState.IsValid)
            {
                db.Entry(superMode).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(superMode);
        }

        // GET: SuperMode/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SuperMode superMode = db.SuperModes.Find(id);
            if (superMode == null)
            {
                return HttpNotFound();
            }
            return View(superMode);
        }

        // POST: SuperMode/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SuperMode superMode = db.SuperModes.Find(id);
            db.SuperModes.Remove(superMode);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SystemNFO/SystemNFO/Views/Employee/AddOrEdit.cshtml
@model SystemNFO.Models.Employee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Employee</h4>
    <hr />
    <div class="row">
        <div class="col-md-6">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <input type="hidden" asp-for="EmployeeId" />
                @Html.LabelFor(model => model.FIO, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FIO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FIO, "", new { @class = "text-danger" })
                </div>
            </div>

            
        </div>
    </div>
    @*<div class="form-group">
        @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-row">
        <div class="form-group col-md-6">
            <input type="submit" value="Submit" class="btn btn-primary btn-block" />
        </div>
        <div class="form-group col-md-6">
            <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i> Back to List</a>
        </div>
    </div>
</div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

SystemNFO/SystemNFO/Views/Employee/Delete.cshtml
@model SystemNFO.Models.Employee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FIO)
        </dd>

    
        @*<dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SystemNFO/SystemNFO/Views/Employee/Details.cshtml
@model SystemNFO.Models.Employee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FIO)
        </dd>

   

        @*<dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EmployeeId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SystemNFO/SystemNFO/Views/Employee/Edit.cshtml
@model SystemNFO.Models.Employee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmployeeId)

        <div class="form-group">
            @Html.LabelFor(model => model.FIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIO, "", new { @class = "text-danger" })
            </div>
        </div>

 
        @*<div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SystemNFO/SystemNFO/Views/Employee/GetEmployees.cshtml
@model IEnumerable<SystemNFO.Models.Employee>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FIO)
        </th>
     
        @*<th>
            @Html.DisplayNameFor(model => model.Position)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FIO)
        </td>
       
        @*<td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EmployeeId }) |
            @Html.ActionLink("Details", "Details", new { id=item.EmployeeId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EmployeeId })
        </td>
    </tr>
}

</table>

SystemNFO/SystemNFO/Views/Employee/Index.cshtml
@model IEnumerable<SystemNFO.Models.Employee>

@{
    ViewBag.Title = "Employee Register";
  
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Добавление", "AddOrEdit")
</p>
<div class="container">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
            <input type="text" id="Search" placeholder="Search" class="form-control" />
        </div>
    </div>
</div>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FIO)
        </th>
       
        @*<th>
            @Html.DisplayNameFor(model => model.Position)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr class="Search">
        <td>
            @Html.DisplayFor(modelItem => item.FIO)
        </td>
    
        @*<td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>*@
        <td>

            @* <a action="Delete" id="@item.EmployeeId" class="text-danger ml-1" onclick="return confirm('Are you sure to delete this record?')"><i class="fa fa-trash-alt fa-lg"></i></a>*@
            <a class="fa fa-marker fa-lg" @Html.ActionLink("|", "AddOrEdit", new { id = item.EmployeeId })></a>
            <a  class="fa fa-trash-alt fa-lg" onclick="return confirm('Are you sure to delete this record?')"
         @Html.ActionLink("|", "Delete", new { id = item.EmployeeId })></a>
           
            @* @Html.ActionLink("Delete", "Delete", new { id = item.EmployeeId })*@
           
        </td>
    </tr>
}

</table>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        function Contains(text_one, text_two) {
            if (text_one.indexOf(text_two) != -1)
                return true;
        }
        $("#Search").keyup(function () {
            var searchText = $("#Search").val().toLowerCase();
            $(".Search").each(function () {
                if (!Contains($(this).text().toLowerCase(), searchText)) {
                    $(this).hide();

                }
                else {
                    $(this).show();
                }     
            });

        });
    });
</script>

SystemNFO/SystemNFO/Views/Employee/OrganizationMode.cshtml
<div class="navbar-collapse collapse">
    <div class="nav navbar-nav">
        <div class="container">
          
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                    <input type="text" id="Search" placeholder="Фильтр по организации" class="form-control" />
                </div>
            </div>
        </div>
    </div>
</div>

<table class="table table-responsive">
    <tr>

        <td>
            @Html.Action("GetOrganizations2", "Organization")
        </td>
        <td>
            <div style="float: right;">


                @Html.Action("GetModes", "SuperMode")

            </div>
        </td>
    
    <tr>
</table>

SystemNFO/SystemNFO/Views/Employee/UserOrganization.cshtml
@{
    ViewBag.Title = "UserEmployee";
}

<div class="navbar-collapse collapse">
    <div class="nav navbar-nav">
        <div class="container">
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                    <input type="text" id="Search1" placeholder="Фильтр по куратору" class="form-control" />

                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                    <input type="text" id="Search" placeholder="Фильтр по организации" class="form-control" />
                </div>
            </div>
        </div>
    </div>
</div>

<table class="table table-responsive">
    <tr>

        <td>
            @Html.Action("GetApplicationUsers", "ApplicationUser")
        </td>
        <td>
            <div style="float: right;">


                @Html.Action("GetOrganizations", "Organization")

            </div>
        </td>
        <td>
            @Html.Action("GetOrganizations", "Cur")
        </td>
<tr>
</table>
<table class="table table-responsive">
    <tr>

        <td>
            <div style="float: right;">
                @Html.Action("GetOrganizations1", "Organization")
            </div>
        </td>
        <td>
            <div style="float: right;">

                @Html.Action("GetOrganizations1", "Cur")
            </div>
        </td>
    <tr>

</table>
    @*<table class="table table-responsive">
            <tr>
                <td>Category</td>
                <td>Product</td>
                <td>Quantity</td>
                <td>Rate</td>
                <td>&nbsp;</td>
            </tr>
            <tr class="mycontainer" id="mainrow">
                <td>
                    <select id="Vidorg" class="pc form-control" onchange="LoadOrganization(this)">
                        <option>Select</option>
                        <option>Микро</option>
                    </select>
                    <span class="error">Select Category</span>
                </td>
                <td>
                    <select id="product" class="product form-control">
                        <option>Select</option>
                    </select>
                    <span class="error">Select product</span>
                </td>
                <td>
                    <input type="text" id="quantity" class="quantity form-control" />
                    <span class="error">Valid quantity required</span>
                </td>
                <td>
                    <input type="text" id="rate" class="rate form-control" />
                    <span class="error">Valid rate required</span>
                </td>
                <td>
                    <input type="button" id="add" value="add" style="width:80px" class="btn btn-success" />
                </td>
            </tr>
        </table>*@

SystemNFO/SystemNFO/Views/Employee/UserOrganization1.cshtml
@{
    ViewBag.Title = "UserEmployee";
}

<div class="navbar-collapse collapse">
    <div class="nav navbar-nav">
        <div class="container">
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                    <input type="text" id="Search1" placeholder="Фильтр по куратору" class="form-control" />

                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                    <input type="text" id="Search" placeholder="Фильтр по организации" class="form-control" />
                </div>
            </div>
        </div>
    </div>
</div>

<table class="table table-responsive">
    <tr>

        <td>
            @Html.Action("GetApplicationUsers", "ApplicationUser")
        </td>

      
    <tr>
</table>
<table class="table table-responsive">
    <tr>


        <td>
            @Html.Action("GetOrganizations", "Cur")
        </td>
<tr>

</table>

<table class="table table-responsive">
    <tr>


        <td>


            @Html.Action("GetOrganizations1", "Cur")

        </td>
    <tr>

</table>