SystemNFO/SystemNFO/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SystemNFO.Models;

namespace SystemNFO.Controllers
{
    public class EventController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Event
        public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        // GET: Event/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Event/Create
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Create4()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create4([Bind(Include = "EventId,Nameevent,Comment,Databegin,Status,Dataend,Dataperenos,Dataplan,Datacontrol,Nadzorfact,Result,Mode")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index4");
            }

            return View(@event);
        }
        // POST: Event/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventId,Nameevent,Comment,Databegin,Status,Dataend,Dataperenos,Dataplan,Datacontrol,Nadzorfact,Result,Mode")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@event);
        }

        // GET: Event/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Event/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventId,Nameevent,Comment,Databegin,Status,Dataend,Dataperenos,Dataplan,Datacontrol,Nadzorfact,Result,Mode")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Event/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SystemNFO/SystemNFO/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlTypes;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SystemNFO.Models;

namespace SystemNFO.Controllers
{
    public class OrganizationController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //[HttpGet]
        //public ActionResult CreateEmp()
        //{ 
        //    SelectList employees = new SelectList(db.Employees, "EmployeeId", "FIO");
        //      ViewBag.Employees = employees;
         
        //}

        public ActionResult Index()
        {
            return View(db.Organizations.ToList());
        }
        public ActionResult Index2()
        {
            return View(db.Events.ToList());
        }
        public ActionResult Index4()
        {
            return View(db.Events.ToList());
        }
        public ActionResult Index3()
        {
            return View(db.SuperModes.ToList());
        }
        public ActionResult GetOrganizations()
        {
            var organizations = db.Organizations.ToList();
            return PartialView(organizations);
        }
        public ActionResult GetOrganizations1()
        {
            var organizations = db.Organizations.ToList();
            return PartialView(organizations);
        }
        public ActionResult GetOrganizations2()
        {
            var organizations = db.Organizations.ToList();
            return PartialView(organizations);
        }
        public ActionResult Index1()
        {
            return View(db.Organizations.ToList());
        }

        [HttpGet]
        public ActionResult ListOrganizations()
        {
            var organizations = db.Organizations.ToList();

            var viewModel = new ListOrganizationViewModel { Organizations = organizations };

            return View(viewModel);
        }
       
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

       
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Create4()
        {
            return View();
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create4([Bind(Include = "EventId,Nameevent,Comment,Databegin,Status,Dataend,Dataperenos,Dataplan,Datacontrol,Nadzorfact,Result,Mode")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index4");
            }

            return View(@event);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrganizationId,Ogrn,Nameorg,Socrnameorg,Status,Vidorg,Category,Risc,Mode")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Organizations.Add(organization);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(organization);
        }
    
        public ActionResult Create1()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create1([Bind(Include = "OrganizationId,Ogrn,Nameorg,Socrnameorg,Status,Vidorg,Category,Risc,Mode")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Organizations.Add(organization);
                db.SaveChanges();
                return RedirectToAction("Index1");
            }

            return View(organization);
        }

        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }
     
        public ActionResult Edit1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrganizationId,Ogrn,Nameorg,Socrnameorg,Status,Vidorg,Category,Risc,Mode")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Entry(organization).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(organization);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit1([Bind(Include = "OrganizationId,Ogrn,Nameorg,Socrnameorg,Status,Vidorg,Category,Risc,Mode")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                db.Entry(organization).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index1");
            }
            return View(organization);
        }

      
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }
        
        public ActionResult Delete1(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Organization organization = db.Organizations.Find(id);
            if (organization == null)
            {
                return HttpNotFound();
            }
            return View(organization);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Organization organization = db.Organizations.Find(id);
            db.Organizations.Remove(organization);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SystemNFO/SystemNFO/Controllers/SuperModeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SystemNFO.Models;

namespace SystemNFO.Controllers
{
    public class SuperModeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SuperMode
        public ActionResult Index()
        {
            return View(db.SuperModes.ToList());
        }
        public ActionResult GetModes()
        {
            var modes = db.SuperModes.ToList();
            return PartialView(modes);
        }
        // GET: SuperMode/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SuperMode superMode = db.SuperModes.Find(id);
            if (superMode == null)
            {
                return HttpNotFound();
            }
            return View(superMode);
        }

        // GET: SuperMode/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SuperMode/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SuperModeId,Ogrn,Date,Document,Vid,Category,Mode,Namemode")] SuperMode superMode)
        {
            if (ModelState.IsValid)
            {
                db.SuperModes.Add(superMode);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(superMode);
        }

        // GET: SuperMode/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SuperMode superMode = db.SuperModes.Find(id);
            if (superMode == null)
            {
                return HttpNotFound();
            }
            return View(superMode);
        }

        // POST: SuperMode/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SuperModeId,Ogrn,Date,Document,Vid,Category,Mode,Namemode")] SuperMode superMode)
        {
            if (ModelState.IsValid)
            {
                db.Entry(superMode).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(superMode);
        }

        // GET: SuperMode/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SuperMode superMode = db.SuperModes.Find(id);
            if (superMode == null)
            {
                return HttpNotFound();
            }
            return View(superMode);
        }

        // POST: SuperMode/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SuperMode superMode = db.SuperModes.Find(id);
            db.SuperModes.Remove(superMode);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SystemNFO/SystemNFO/Views/Organization/Create.cshtml
@model SystemNFO.Models.Organization

@{
    ViewBag.Title = "Организации";
}

<h2>Добавить организацию</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Организация</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Ogrn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ogrn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ogrn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nameorg, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nameorg, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nameorg, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Socrnameorg, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Socrnameorg, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Socrnameorg, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="dropdown">
        <div class="form-group">
            @Html.LabelFor(model => model.Vidorg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li></li>
                    <li><a href="#">Назначение организаций</a></li>
                    <li><a href="#">Внутренний реестр организаций</a></li>
                </ul>
                @Html.EditorFor(model => model.Vidorg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vidorg, "", new { @class = "text-danger" })

            </div>
        </div>
    </div>

        


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Назад к списку", "Index")
    </div>

SystemNFO/SystemNFO/Views/Organization/Delete.cshtml
@model SystemNFO.Models.Organization

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление организации</h2>

<h3>Вы действительно хотите удалить эту организацию?</h3>
<div>
    <h4>Удаление организации</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ogrn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ogrn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nameorg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nameorg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Socrnameorg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Socrnameorg)
        </dd>

      
        <dt>
            @Html.DisplayNameFor(model => model.Vidorg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vidorg)
        </dd>

    

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад к списку", "Index")
        </div>
    }
</div>

SystemNFO/SystemNFO/Views/Organization/Index3.cshtml
@model IEnumerable<SystemNFO.Models.SuperMode>

@*@{
    ViewBag.Title = "Index";
}*@

<div class="container">
    <div class="master">
        <h2>Order</h2>
        <table class="table table-responsive">
            <tr>
                <td>ОГРН</td>
                <td>
                    <input type="text" id="orderNo" class="form-control" />
                    <span class="error">Order no required</span>
                </td>
                <td>Сокр. наименование</td>
                <td>
                    <input type="text" id="orderDate" class="form-control" />
                    <span class="error">Valid order date required (ex: MM-dd-yyyy)</span>
                </td>
                <td>Вид</td>
                <td>
                    <select id="Vidorg" class="pc form-control" onchange="LoadOrganization(this)">
                        <option>Микрофинансовая компания</option>
                        <option>Сельскохозяйственный кооператив</option>
                        <option>Жилищный накопительный кооператив</option>
                        <option>Кредитный потребительский кооператив</option>
                        <option>Саморегулируемая органиазция</option>
                        <option>AO Ломбард</option>

                    </select>
                    <span class="error">Select Category</span>
                </td>
                <td>Категория</td>
                <td>
                    <select id="product" class="product form-control">
                        <option>Крупные и системнозначимые МФИ и СРО</option>
                        <option>Крупные и системнозначимые КПК и СКПК</option>
                        <option>Другие</option>
                    </select>
                    <span class="error">Select product</span>
                </td>
            </tr>
            <tr>
                <td>Риск-профиль</td>
                <td>
                    <select id="product" class="product form-control">
                        <option>Оранжевый</option>
                        <option>Красный</option>
                        <option>Зеленый</option>
                    </select>
                    <span class="error">Select product</span>
                </td>
                <td>Документ</td>
                <td colspan="3">
                    <textarea id="description" class="form-control"></textarea>
                </td>
                <td>Дата от:</td>
                <td>
                    <input type="date" id="orderDate" class="form-control" />
                    <span class="error">Valid order date required (ex: MM-dd-yyyy)</span>
                </td>
                <td>Режим</td>
                <td>
                    <input type="text" id="orderDate" class="form-control" />
                    <span class="error">Valid order date required (ex: MM-dd-yyyy)</span>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="button" id="add" value="Сохранить" style="width:90px" class="btn btn-success" />
                </td>
                <td>
                    <input type="button" id="add" value="Отменить" style="width:90px" class="btn btn-success" />
                </td>
            </tr>
        </table>
    </div>
   
</div>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="~/Scripts/myScripts.js"></script>
<script type="text/javascript">
    $(function () {
        $('#orderDate').datepicker({
            dateFormat: 'mm-dd-yy'
        })
    })
</script>
<style>
    span.error {
        display: block;
        visibility: hidden;
        color: red;
        font-size: 90%;
    }

    tr.error {
        background-color: rgba(255,0,0,0.35);
    }
</style>




<p>
    @Html.ActionLink("Добавить", "Create", "SuperMode")
</p>
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.Ogrn)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Document)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Namemode)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.Ogrn)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Document)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Namemode)
            </td>
            @*<td>
                @Html.ActionLink("Редактировать", "Edit", "SuperMode", new { id = item.SuperModeId })
                @Html.ActionLink("Details", "Details", new { id = item.SuperModeId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.SuperModeId })
            </td>*@
        </tr>
    }

</table>

SystemNFO/SystemNFO/Views/Organization/Index4.cshtml
@model IEnumerable<SystemNFO.Models.Event>
@*@{
        ViewBag.Title = "Index";
    }*@

<div class="container">
    <div class="master">
        <h2>Order</h2>
        <table class="table table-responsive">
            <tr>
                <td>ОГРН</td>
                <td>
                    <input type="text" id="orderNo" class="form-control" />
                    <span class="error">Order no required</span>
                </td>
                <td>Сокр. наименование</td>
                <td>
                    <input type="text" id="orderDate" class="form-control" />
                    <span class="error">Valid order date required (ex: MM-dd-yyyy)</span>
                </td>
                <td>Вид</td>
                <td>
                    <select id="Vidorg" class="pc form-control" onchange="LoadOrganization(this)">
                        <option>Микрофинансовая компания</option>
                        <option>Сельскохозяйственный кооператив</option>
                        <option>Жилищный накопительный кооператив</option>
                        <option>Кредитный потребительский кооператив</option>
                        <option>Саморегулируемая органиазция</option>
                        <option>AO Ломбард</option>

                    </select>
                    <span class="error">Select Category</span>
                </td>
                <td>Категория</td>
                <td>
                    <select id="product" class="product form-control">
                        <option>Крупные и системнозначимые МФИ и СРО</option>
                        <option>Крупные и системнозначимые КПК и СКК</option>
                    </select>
                    <span class="error">Select product</span>
                </td>
            </tr>
            <tr>
                <td>Риск-профиль</td>
                <td>
                    <select id="product" class="product form-control">
                        <option>Оранжевый</option>
                        <option>Красный</option>
                        <option>Зеленый</option>
                    </select>
                    <span class="error">Select product</span>
                </td>
              
                <td>Дата изменения:</td>
                <td>
                    <input type="date" id="orderDate" class="form-control" />
                    <span class="error">Valid order date required (ex: MM-dd-yyyy)</span>
                </td>
                <td>Режим</td>
                <td>
                    <input type="text" id="orderDate" class="form-control" />
                    <span class="error">Valid order date required (ex: MM-dd-yyyy)</span>
                </td>
            </tr>
            @*<tr>
                <td>
                    <input type="button" id="add" value="Сохранить" style="width:90px" class="btn btn-success" />
                </td>
                <td>
                    <input type="button" id="add" value="Отменить" style="width:90px" class="btn btn-success" />
                </td>

            </tr>*@
        </table>
    </div>
    <div style="padding:10px 0; text-align:right">
        <input id="submit" type="button" value="Отчет" class="btn btn-warning" style="padding:10px 20px" />
    </div>
</div>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="~/Scripts/myScripts.js"></script>
<script type="text/javascript">
    $(function () {
        $('#orderDate').datepicker({
            dateFormat: 'mm-dd-yy'
        })
    })
</script>
<style>
    span.error {
        display: block;
        visibility: hidden;
        color: red;
        font-size: 90%;
    }

    tr.error {
        background-color: rgba(255,0,0,0.35);
    }
</style>


@*<h2>Index</h2>*@

@{
    ViewBag.Title = "Мероприятия";
}

<h2>Мероприятия</h2>

<p>
    @Html.ActionLink("Добавить мероприятие", "Create4")
</p>
<div class="panel panel-default">
    <div class="panel-heading">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li class="active"><a href="#home" role="tab" data-toggle="tab">Текущие</a></li>
            <li><a href="#profile" role="tab" data-toggle="tab">Прошедшие</a></li>
            <li><a href="#profile" role="tab" data-toggle="tab">Удаленные</a></li>

        </ul>

    </div>

    <!-- Tab panes + Panel body -->
    <div class="panel-body tab-content">
        <div class="tab-pane active" id="home">
            <table class="table">

                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Nameevent)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Comment)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Databegin)
                    </th>
                   
                    <th>
                        @Html.DisplayNameFor(model => model.Dataend)
                    </th>

                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nameevent)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Comment)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Databegin)
                        </td>
                       
                        <td>
                            @Html.DisplayFor(modelItem => item.Dataend)
                        </td>

                        <td>
                            @Html.ActionLink("Редактировать", "Index", "Event")
                            @Html.ActionLink("Удалить", "Delete", "Event")       
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

SystemNFO/SystemNFO/Views/Organization/ListOrganizations.cshtml
@model SystemNFO.Models.ListOrganizationViewModel

@Html.DropDownListFor(m => m.Organizations, new SelectList(Model.Organizations, "OrganizationId", "Vidorg"), " ")